const Names = {

    firstNames: [

        // 🇫🇷 Français
        "Alexandre",
        "Antoine",
        "Arthur",
        "Baptiste",
        "Benjamin",
        "Clément",
        "Corentin",
        "Enzo",
        "Étienne",
        "Gabriel",
        "Hugo",
        "Jules",
        "Léo",
        "Lucas",
        "Louis",
        "Mathieu",
        "Mathis",
        "Maxime",
        "Nathan",
        "Nicolas",
        "Noah",
        "Paul",
        "Raphaël",
        "Romain",
        "Théo",
        "Thomas",
        "Valentin",
        "Victor",
        "Yanis",
        "Yohan",

        // 🇪🇸 Espagnols
        "Alejandro",
        "Álvaro",
        "Andrés",
        "Antonio",
        "Carlos",
        "Diego",
        "Eduardo",
        "Fernando",
        "Francisco",
        "Gonzalo",
        "Javier",
        "Jorge",
        "José",
        "Juan",
        "Luis",
        "Manuel",
        "Marcos",
        "Mario",
        "Miguel",
        "Pablo",
        "Pedro",
        "Raúl",
        "Sergio",
        "Ángel",
        "Adrián",

        // 🇬🇧 Anglais
        "Adam",
        "Alexander",
        "Ben",
        "Charlie",
        "Daniel",
        "David",
        "Edward",
        "Ethan",
        "George",
        "Harry",
        "Henry",
        "Jack",
        "Jacob",
        "James",
        "Jamie",
        "Joseph",
        "Joshua",
        "Liam",
        "Oliver",
        "Oscar",
        "Ryan",
        "Samuel",
        "Scott",
        "Thomas",
        "William",

        // 🇮🇹 Italiens
        "Alessandro",
        "Andrea",
        "Angelo",
        "Antonio",
        "Carlo",
        "Davide",
        "Domenico",
        "Emanuele",
        "Fabio",
        "Federico",
        "Filippo",
        "Francesco",
        "Gabriele",
        "Giancarlo",
        "Giorgio",
        "Giovanni",
        "Lorenzo",
        "Luca",
        "Marco",
        "Matteo",
        "Niccolò",
        "Paolo",
        "Pietro",
        "Riccardo",
        "Stefano",

        // 🇩🇪 Allemands
        "Adrian",
        "Alexander",
        "Andreas",
        "Christian",
        "Christoph",
        "Daniel",
        "David",
        "Felix",
        "Florian",
        "Friedrich",
        "Hans",
        "Jan",
        "Jonas",
        "Julian",
        "Karl",
        "Leon",
        "Lukas",
        "Max",
        "Maximilian",
        "Niklas",
        "Paul",
        "Sebastian",
        "Simon",
        "Tobias",
        "Wolfgang",

        // 🇵🇹 Portugais
        "Afonso",
        "André",
        "Bruno",
        "Diogo",
        "Duarte",
        "Fábio",
        "Gonçalo",
        "Guilherme",
        "Hugo",
        "João",
        "Jorge",
        "José",
        "Leandro",
        "Manuel",
        "Marco",
        "Miguel",
        "Nuno",
        "Pedro",
        "Rafael",
        "Ricardo",
        "Rodrigo",
        "Rui",
        "Tiago",
        "Tomás",
        "Vasco",

        // 🇳🇱 Néerlandais
        "Bram",
        "Daan",
        "Dirk",
        "Jeroen",
        "Joost",
        "Lars",
        "Luuk",
        "Maarten",
        "Max",
        "Niels",
        "Pieter",
        "Ruben",
        "Sander",
        "Sem",
        "Thijs",

        // 🇧🇪 Belges
        "Arnaud",
        "Bastien",
        "Benoît",
        "Damien",
        "François",
        "Geoffrey",
        "Jérôme",
        "Kevin",
        "Loïc",
        "Quentin",
        "Simon",
        "Thibault",
        "Xavier",
        "Yann",
        "Thomas",

        // 🇧🇷 Brésiliens
        "Arthur",
        "Caio",
        "Carlos",
        "Davi",
        "Diego",
        "Eduardo",
        "Enzo",
        "Felipe",
        "Fernando",
        "Gabriel",
        "Gustavo",
        "João",
        "Lucas",
        "Matheus",
        "Murilo",
        "Nicolas",
        "Rafael",
        "Renan",
        "Thiago",
        "Vinícius",

        // 🇦🇷 Argentins
        "Agustín",
        "Alejandro",
        "Bruno",
        "Cristian",
        "Diego",
        "Facundo",
        "Federico",
        "Gonzalo",
        "Joaquín",
        "Julián",
        "Leandro",
        "Lucas",
        "Martín",
        "Matías",
        "Maximiliano",
        "Nicolás",
        "Pablo",
        "Rodrigo",
        "Santiago",
        "Tomás",

        // 🇲🇽 / 🇨🇴 / 🇨🇱 Amérique latine
        "Adrián",
        "Alonso",
        "Ángel",
        "Brayan",
        "Camilo",
        "Cristóbal",
        "Emiliano",
        "Esteban",
        "Felipe",
        "Germán",
        "Héctor",
        "Iván",
        "Jhon",
        "Mauricio",
        "Miguel",
        "Óscar",
        "Renato",
        "Sebastián",
        "Valentín",
        "Vicente",

        // 🌍 Afrique
        "Abdou",
        "Abdoulaye",
        "Amadou",
        "Bamba",
        "Cheikh",
        "Ibrahima",
        "Idrissa",
        "Ismaël",
        "Kader",
        "Karim",
        "Mamadou",
        "Moussa",
        "Oumar",
        "Sadio",
        "Souleymane",
        "Yacine",
        "Yannick",
        "Youssouf",
        "Zakaria",
        "Zoumana",

        // 🇲🇦 Maghreb
        "Adel",
        "Amine",
        "Anis",
        "Bilal",
        "Hamza",
        "Hicham",
        "Imran",
        "Mehdi",
        "Nabil",
        "Rachid",
        "Samir",
        "Sofiane",
        "Tarik",
        "Walid",
        "Yassine",

        // 🇯🇵 Japonais
        "Akira",
        "Daichi",
        "Haruto",
        "Hayato",
        "Hiroki",
        "Hiroshi",
        "Kaito",
        "Kenji",
        "Ren",
        "Riku",
        "Shota",
        "Sota",
        "Takumi",
        "Yamato",
        "Yuki",

        // 🇰🇷 Coréens
        "Dong-hyun",
        "Hyun-woo",
        "Jae-min",
        "Ji-ho",
        "Ji-hoon",
        "Jin-woo",
        "Jun-ho",
        "Min-jae",
        "Min-ho",
        "Seung-ho",
        "Sung-min",
        "Tae-hyun",
        "Woo-jin",
        "Young-ho",
        "Jun",

        // 🇺🇸 Internationaux
        "Aaron",
        "Adrian",
        "Brandon",
        "Cameron",
        "Dylan",
        "Eric",
        "Jason",
        "Jordan",
        "Justin",
        "Kevin",
        "Kyle",
        "Logan",
        "Mason",
        "Nathaniel",
        "Tyler"

    ],



    lastNames: [

        // 🇫🇷 Français
        "Martin",
        "Bernard",
        "Dubois",
        "Thomas",
        "Robert",
        "Richard",
        "Petit",
        "Durand",
        "Leroy",
        "Moreau",
        "Simon",
        "Laurent",
        "Lefebvre",
        "Michel",
        "Garcia",
        "David",
        "Bertrand",
        "Roux",
        "Vincent",
        "Fournier",
        "Morel",
        "Girard",
        "André",
        "Lefèvre",
        "Mercier",
        "Dupont",
        "Lambert",
        "Bonnet",
        "François",
        "Martinez",

        // 🇪🇸 Espagnols
        "García",
        "Fernández",
        "González",
        "Rodríguez",
        "López",
        "Martínez",
        "Sánchez",
        "Pérez",
        "Martín",
        "Gómez",
        "Ruiz",
        "Díaz",
        "Moreno",
        "Muñoz",
        "Álvarez",
        "Romero",
        "Alonso",
        "Navarro",
        "Torres",
        "Domínguez",
        "Vázquez",
        "Ramos",
        "Ramírez",
        "Vega",
        "Ortega",

        // 🇬🇧 Anglais
        "Smith",
        "Jones",
        "Taylor",
        "Brown",
        "Williams",
        "Wilson",
        "Johnson",
        "Davies",
        "Patel",
        "Robinson",
        "Wright",
        "Thompson",
        "Evans",
        "Walker",
        "White",
        "Roberts",
        "Green",
        "Hall",
        "Thomas",
        "Clarke",
        "Jackson",
        "Wood",
        "Harris",
        "Edwards",
        "Turner",

        // 🇮🇹 Italiens
        "Rossi",
        "Russo",
        "Ferrari",
        "Esposito",
        "Bianchi",
        "Romano",
        "Colombo",
        "Ricci",
        "Marino",
        "Greco",
        "Bruno",
        "Gallo",
        "Conti",
        "De Luca",
        "Mancini",
        "Costa",
        "Giordano",
        "Rizzo",
        "Lombardi",
        "Moretti",
        "Barbieri",
        "Fontana",
        "Santoro",
        "Mariani",
        "Rinaldi",

        // 🇩🇪 Allemands
        "Müller",
        "Schmidt",
        "Schneider",
        "Fischer",
        "Weber",
        "Meyer",
        "Wagner",
        "Becker",
        "Schulz",
        "Hoffmann",
        "Schäfer",
        "Koch",
        "Bauer",
        "Richter",
        "Klein",
        "Wolf",
        "Schröder",
        "Neumann",
        "Schwarz",
        "Zimmermann",
        "Braun",
        "Krüger",
        "Hofmann",
        "Hartmann",
        "Lange",

        // 🇵🇹 Portugais
        "Silva",
        "Santos",
        "Ferreira",
        "Pereira",
        "Oliveira",
        "Costa",
        "Rodrigues",
        "Martins",
        "Jesus",
        "Sousa",
        "Fernandes",
        "Gonçalves",
        "Gomes",
        "Lopes",
        "Marques",
        "Alves",
        "Almeida",
        "Ribeiro",
        "Pinto",
        "Carvalho",
        "Teixeira",
        "Moreira",
        "Correia",
        "Mendes",
        "Nunes",

        // 🇳🇱 Néerlandais
        "De Jong",
        "Jansen",
        "De Vries",
        "Van den Berg",
        "Van Dijk",
        "Bakker",
        "Visser",
        "Smit",
        "Meijer",
        "De Boer",
        "Mulder",
        "De Groot",
        "Bos",
        "Vos",
        "Peters",

        // 🇧🇪 Belges
        "Peeters",
        "Janssens",
        "Maes",
        "Jacobs",
        "Mertens",
        "Willems",
        "Claes",
        "Goossens",
        "De Smet",
        "Vermeulen",
        "De Clercq",
        "Vandenberghe",
        "Lemaire",
        "Dupuis",
        "Leclercq",

        // 🇧🇷 Brésiliens
        "Oliveira",
        "Souza",
        "Silva",
        "Santos",
        "Lima",
        "Costa",
        "Pereira",
        "Ferreira",
        "Almeida",
        "Ribeiro",
        "Carvalho",
        "Gomes",
        "Martins",
        "Barbosa",
        "Rocha",
        "Dias",
        "Nascimento",
        "Mendes",
        "Moreira",
        "Teixeira",

        // 🇦🇷 Argentins
        "González",
        "Rodríguez",
        "Gómez",
        "Fernández",
        "López",
        "Martínez",
        "Díaz",
        "Pérez",
        "Sánchez",
        "Romero",
        "Sosa",
        "Álvarez",
        "Torres",
        "Ruiz",
        "Ramírez",
        "Flores",
        "Acosta",
        "Benítez",
        "Medina",
        "Herrera",

        // 🇲🇽 / 🇨🇴 / 🇨🇱
        "Hernández",
        "Castillo",
        "Mendoza",
        "Vargas",
        "Rojas",
        "Cortés",
        "Navarro",
        "Molina",
        "Suárez",
        "Morales",
        "Jiménez",
        "Gutiérrez",
        "Ortega",
        "Cabrera",
        "Fuentes",
        "Espinoza",
        "Valencia",
        "Paredes",
        "Vega",
        "Campos",

        // 🌍 Afrique
        "Diop",
        "Ndiaye",
        "Fall",
        "Sarr",
        "Ba",
        "Diallo",
        "Camara",
        "Traoré",
        "Konaté",
        "Coulibaly",
        "Keita",
        "Kone",
        "Touré",
        "Fofana",
        "Cissé",
        "Sylla",
        "Diarra",
        "Kouyaté",
        "Mendy",
        "Seck",

        // 🇲🇦 Maghreb
        "Alaoui",
        "Bennani",
        "Benali",
        "El Amrani",
        "El Idrissi",
        "Fassi",
        "Haddad",
        "Hamdi",
        "Khalil",
        "Mansouri",
        "Meziane",
        "Rahmani",
        "Saidi",
        "Tazi",
        "Zeroual",

        // 🇯🇵 Japonais
        "Sato",
        "Suzuki",
        "Takahashi",
        "Tanaka",
        "Watanabe",
        "Ito",
        "Yamamoto",
        "Nakamura",
        "Kobayashi",
        "Kato",
        "Yoshida",
        "Yamada",
        "Sasaki",
        "Yamaguchi",
        "Matsumoto",

        // 🇰🇷 Coréens
        "Kim",
        "Lee",
        "Park",
        "Choi",
        "Jung",
        "Kang",
        "Cho",
        "Yoon",
        "Jang",
        "Lim",
        "Han",
        "Shin",
        "Seo",
        "Kwon",
        "Hwang",

        // 🇺🇸 Internationaux
        "Anderson",
        "Clark",
        "Lewis",
        "Walker",
        "Young",
        "Allen",
        "King",
        "Scott",
        "Green",
        "Baker",
        "Adams",
        "Nelson",
        "Carter",
        "Mitchell",
        "Roberts"

    ],



    getRandomFirstName() {

        return this.firstNames[
            Math.floor(
                Math.random() *
                this.firstNames.length
            )
        ];

    },



    getRandomLastName() {

        return this.lastNames[
            Math.floor(
                Math.random() *
                this.lastNames.length
            )
        ];

    },



    getRandomFullName() {

        return (
            this.getRandomFirstName()
            +
            " "
            +
            this.getRandomLastName()
        );

    }

};
